"""users table

Revision ID: 4508bbdd471c
Revises: 
Create Date: 2019-04-27 15:27:21.008394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4508bbdd471c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullName', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('nickname', sa.String(length=32), nullable=True),
    sa.Column('phoneNumber', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('aboutMe', sa.Text(length=600), nullable=True),
    sa.Column('dateOfBirth', sa.Date(), nullable=True),
    sa.Column('dateOfReg', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('phoneNumber')
    )
    op.create_index(op.f('ix_user_dateOfReg'), 'user', ['dateOfReg'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_dateOfReg'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
